//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaYeltic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CatSucursales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatSucursales()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
        
        [DisplayName("Sucursal")]
        public int idSucursal { get; set; }
        [DisplayName("Nombre Sucursal")]
        public string varSursal { get; set; }
        [DisplayName("Dirección Sucursal")]
        public string varDireccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
