//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaYeltic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_PruebaYelticEntities : DbContext
    {
        public BD_PruebaYelticEntities()
            : base("name=BD_PruebaYelticEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatPuestos> CatPuestos { get; set; }
        public virtual DbSet<CatSucursales> CatSucursales { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
