//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaYeltic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Usuarios
    {
        [DisplayName("ID Usuario")]
        public int idUsuario { get; set; }
        [DisplayName("Sucursal")]
        public int idSucursal { get; set; }
        [DisplayName("Puesto")]
        public int idPuesto { get; set; }
        [DisplayName("Nombre Usuario")]
        public string varNombre { get; set; }
        [DisplayName("Primer Apellido")]
        public string varPrimerApellido { get; set; }
        [DisplayName("Segundo Apellido")]
        public string varSegundoApellido { get; set; }
        [DisplayName("Sexo")]
        public string varSexo { get; set; }
        [DisplayName("Usuario Activo")]
        public bool bitActivo { get; set; }
    
        public virtual CatPuestos CatPuestos { get; set; }
        public virtual CatSucursales CatSucursales { get; set; }
    }
}
